import { Option } from "../components/inputSelect/InputSelect";

const languages: Option[] = [
  { value: "en", label: "English" },
  { value: "fr", label: "French" },
  { value: "de", label: "German" },
  { value: "es", label: "Spanish" },
  { value: "it", label: "Italian" },
  { value: "pt", label: "Portuguese" },
  { value: "nl", label: "Dutch" },
  { value: "ar", label: "Arabic" },
  { value: "gd", label: "Gaelic" },
  { value: "rm", label: "Rhaeto-Romanic" },
  { value: "eu", label: "Basque" },
  { value: "bg", label: "Bulgarian" },
  { value: "be", label: "Belarusian" },
  { value: "ca", label: "Catalan" },
  { value: "hr", label: "Croatian" },
  { value: "cs", label: "Czech" },
  { value: "da", label: "Danish" },
  { value: "et", label: "Estonian" },
  { value: "fo", label: "Faeroese" },
  { value: "fa", label: "Farsi" },
  { value: "fi", label: "Finnish" },
  { value: "af", label: "Afrikaans" },
  { value: "sq", label: "Albanian" },
  { value: "sv", label: "Swedish" },
  { value: "th", label: "Thai" },
  { value: "ts", label: "Tsonga" },
  { value: "tn", label: "Tswana" },
  { value: "tr", label: "Turkish" },
  { value: "uk", label: "Ukrainian" },
  { value: "ur", label: "Urdu" },
  { value: "ve", label: "Venda" },
  { value: "vi", label: "Vietnamese" },
  { value: "xh", label: "Xhosa" },
  { value: "zu", label: "Zulu" },
  { value: "sr", label: "Serbian" },
  { value: "sk", label: "Slovak" },
  { value: "sl", label: "Slovenian" },
  { value: "ja", label: "Japanese" },
  { value: "ko", label: "Korean" },
  { value: "lv", label: "Latvian" },
  { value: "lt", label: "Lithuanian" },
  { value: "mk", label: "FYRO Macedonian ms Malaysian" },
  { value: "mt", label: "Maltese" },
  { value: "no", label: "Norwegian" },
  { value: "pl", label: "Polish" },
  { value: "ro", label: "Romanian" },
  { value: "ru", label: "Russian" },
  { value: "el", label: "Greek" },
  { value: "he", label: "Hebrew" },
  { value: "hi", label: "Hindi" },
  { value: "hu", label: "Hungarian" },
  { value: "is", label: "Icelandic" },
  { value: "id", label: "Indonesian" },
  { value: "zh", label: "Chinese" },
];

const getLanguages = (): Option[] => {
  return languages;
};

export default getLanguages;
